### ISSUE TITLE
Account signed out

### ISSUE THREAD

**Issue by PedrinBlox** [iEventz/free-bundle-buyer-roblox#1]
after i runt my account got signed out anyone with the same problem?
everytime i run it signs out

**Comment by iEventz** [comment]
I hacked u bozo

**Comment by PedrinBlox** [comment]
nooooo

**Comment by NarCodingLUA** [comment]
rest in piss

**Comment by efenatuyo** [comment]
@iEventz how do u make this small thing in 400 lines I made it in under 60 lines

**Comment by xbfj** [comment]
🥶

**Comment by iEventz** [comment]
for the ppl dming me it was a joke bro it does not log u
